### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by richardeigenmann** [IGNF/wxfreechart#1]
I am trying to compile on OpenSUSE Leap with wxWidgets 3.0.
After cloning and mkdir build && cd build && cmake .. && make I get the following error:

In file included from /richi/Src/wxfreechart/src/areadraw.cpp:10:0:
/richi/Src/wxfreechart/include/wx/areadraw.h:149:29: error: using typedef-name ‘AreaDrawMap’ after ‘class’
 class WXDLLIMPEXP_FREECHART AreaDrawMap;
                             ^
In file included from /usr/include/wx-3.0/wx/wx.h:20:0,
                 from /richi/Src/wxfreechart/include/wx/wxfreechartdefs.h:25,
                 from /richi/Src/wxfreechart/include/wx/areadraw.h:13,
                 from /richi/Src/wxfreechart/src/areadraw.cpp:10:
/richi/Src/wxfreechart/include/wx/areadraw.h:148:69: note: ‘AreaDrawMap’ has a previous declaration here
 WX_DECLARE_HASH_MAP(int, AreaDraw _, wxIntegerHash, wxIntegerEqual, AreaDrawMap);
                                                                     ^
src/CMakeFiles/wxfreechart.dir/build.make:62: recipe for target 'src/CMakeFiles/wxfreechart.dir/areadraw.cpp.o' failed
make[2]: *_\* [src/CMakeFiles/wxfreechart.dir/areadraw.cpp.o] Error 1
CMakeFiles/Makefile2:103: recipe for target 'src/CMakeFiles/wxfreechart.dir/all' failed
make[1]: **\* [src/CMakeFiles/wxfreechart.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

Commenting off the line 149 in the file areadraw.h seems to fix this.

What is the right way to fix this?

Seems the problem has been seen before: https://forums.wxwidgets.org/viewtopic.php?t=37893
